export const environment = {
  production: true,
  secretKey : "M@ckiNterViiew",
  domain : "",
  emailRegex : /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  phoneNoRegex : /^(\+91[\-\s]?)?[0]?(91)?[6789]\d{9}$/,
  nameRegex : /^[A-Za-z\s'\-]+$/,
  artistCommission:0.90,
  keyid:'rzp_test_Cm5LAJVx36wzvK',
  adminMail:'vinay.admin@yopmail.com',
  appName : 'Artlist',
  states:[
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Lakshadweep",
    "Delhi",
    "Puducherry"
  ],
  languages:[
    {"name": "Hindi"},
    {"name": "Bengali"},
    {"name": "English"},
    {"name": "Telugu"},
    {"name": "Marathi"},
    {"name": "Tamil"},
    {"name": "Urdu"},
    {"name": "Gujarati"},
    {"name": "Kannada"},
    {"name": "Odia"},
    {"name": "Punjabi"},
    {"name": "Malayalam"},
    {"name": "Assamese"},
    {"name": "Sanskrit"},
    {"name": "Konkani"},
    {"name": "Nepali"},
    {"name": "Manipuri"},
    {"name": "Sindhi"},
    {"name": "Maithili"},
    {"name": "Dogri"},
    {"name": "Bodo"},
    {"name": "Kashmiri"},
    {"name": "Santhali"}
  ],
  skillList:[
    { name: "Director" },
    { name: "Producer" },
    { name: "Screenwriter" },
    { name: "Cinematographer/Director of Photography (DP)" },
    { name: "Actor/Actress" },
    { name: "Editor" },
    { name: "Costume Designer" },
    { name: "Makeup and Hair Stylists" },
    { name: "Production Designer/Art Director" },
    { name: "Location Manager" },
    { name: "Sound Engineer" },
    { name: "Composer" },
    { name: "Music Director" },
    { name: "Choreographer" },
    { name: "Dancer" },
    { name: "Stunt Coordinator" },
    { name: "Special Effects Supervisor" },
    { name: "Visual Effects (VFX) Artists" },
    { name: "Dialect Coach" },
    { name: "Production Manager" },
    { name: "Casting Director" },
    { name: "Script Supervisor" },
    { name: "Gaffer" },
    { name: "Key Grip" },
    { name: "Assistant Director (1st AD, 2nd AD)" },
    { name: "Production Assistant (PA)" },
    { name: "Set Decorator" },
    { name: "Wardrobe Supervisor" },
    { name: "Animal Wrangler" },
    { name: "DIT (Digital Imaging Technician)" },
    { name: "Colorist" },
    { name: "Grip" },
    { name: "Best Boy" },
    { name: "Boom Operator" },
    { name: "Caterer/Craft Service" },
    { name: "Legal and Clearance Team" },
    { name: "Publicist" },
    { name: "Singer" },
    { name: "Musician" },
    { name: "Sound Recordist" },
    { name: "Sound designer" },
    { name: "Lighting Designer" },
    { name: "Prop Master" },
    { name: "Storyboard Artist" },
    { name: "Location Scout" },
    { name: "Dance Instructor" },
    { name: "Fight Choreographer" },
    { name: "SFX Makeup Artist" },
    { name: "Foley Artist" },
    { name: "ADR Supervisor" },
    { name: "Post-Production Supervisor" },
    { name: "Public Relations Manager" },
    { name: "Film Editor" },
    { name: "Line producer" },
    { name: "Marketing Director" },
    { name: "Set Builder" },
    { name: "Cinematographer's Assistant" },
    { name: "Background performers" }
    ],
  payDetails:{
    "image": "https://media.geeksforgeeks.org/wp-content/uploads/20210806114908/dummy-200x200.png",
    "color":"#2300a3"
  }
};
